repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: mixed-line-ending

  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
      - id: go-fmt
      - id: go-mod-tidy
      - id: go-build
        args: ['-o', '/dev/null']

  - repo: https://github.com/tekwizely/pre-commit-golang
    rev: v1.0.0-rc.1
    hooks:
      - id: go-vet-repo-mod

  - repo: local
    hooks:
      - id: terraform-fmt
        name: terraform fmt
        entry: terraform
        args: ['-chdir=infrastructure', 'fmt', '-check']
        language: system
        files: \.tf$
        pass_filenames: false
